version: "2"

services:
    app:
        build:
            context: docker/dev
        container_name: enmarche_app
        depends_on:
            - db
            - redis
        volumes:
            - .:/app
        networks:
            - enmarche
            - default

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:3.2

networks:
    enmarche:
        external:
            name: enmarche
